kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/part-of: {{ .Values.app.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
