---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.namespace}}-${{values.componentId}}
  namespace: janus-argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  source:
    repoURL: ${{values.sourceRepository}}
    path: ./helm/summit-connect-challenge
    targetRevision: ${{values.defaultBranch}}
    # adding those helm values here allows the helm
    # chart to be somewhere different and it doesn't
    # have to be deployed in each repo with backstage
    helm:
      values: |
        app:
          name: ${{values.componentId}}
          namespace: ${{values.namespace}}
          clusterId: ${{values.clusterId}}

  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy      
